name: Nightly build Android and Dockerfile

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build_environment
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: false
        tags: build_environment:latest

    - name: build_simutrans_within_container
      run: |
        docker run -d --name build_container build_environment:latest sleep 3600
        docker exec build_container ./build.sh simutrans
        docker cp build_container:/android-sdl/project/app/build/outputs/apk/release/app-release.apk .
        docker container stop build_container
        docker container rm build_container
    
    - name: Rename result
      run:  mv app-release.apk simuandroid-multiabi-nightly.apk